### ISSUE TITLE
Black Screen on connection

### ISSUE THREAD

**Issue by CallumWalley** [nesi/nesi-virtual-desktops#1]
Command runs fine on cluster.
Server starts fine, websocket starts fine.
Black screen after clicking the 'connect' button in web browser.

**Comment by jennan** [comment]
I have noticed that starting a desktop creates a `~/.Xauthtority ` file but no `~/.Xauthority` file. Could it be related?

**Comment by CallumWalley** [comment]
Temporarily fixed problem by adding `-C` (no home) flag to `start_vdt`. Obviously isn't ideal but confirms that it is to do with something in the home directory.

**Comment by CallumWalley** [comment]
Narrowed the problem down to the files `.cache` and `.config`.

- Either of these directories existing will cause the black screen issue.
- Directories can be completely empty.
- A new `.cache` and `.config` are created whenever a desktop is started.
- Changing default path does not appear to change anything.

I've fixed this temporarily by adding a `rm -rf .cache .config` in `start_vdt`. This will delete any desktop preferences.

**Comment by CallumWalley** [comment]
It's to do with the permissions.

- `.config` `.cache` possibly others need to be 0700
- `.Xauthority`, `.ICEauthority` possibly others need to be 0600

Something. Possibly singularity is messing with the permissions. Changing them to wrong.
